[UPD] Update account_financial_report.pot
[a0cb11bb] [FIX] Journal ledger wizard to inherit from abstract report wizard

Fixes
    AttributeError: type object 'journal.ledger.report.wizard' has no attribute
    'button_export_xlsx'

Regression of #735