[18.0][FIX] account_financial_report: limit unaffected_earnings_account search to one
_compute_unaffected_earnings_account in trial_balance_wizard and
general_ledger_wizard assigns a Many2one field but the search domain
("company_ids", "in", ...) on account.account can match multiple
records in multi-company setups (equity_unaffected accounts typically
exist per company). Without limit=1 the assignment raises:

  ValueError: Wrong value for <wizard>.unaffected_earnings_account:
              account.account(X, Y)

Add limit=1 to both wizards. The 19.0 branch is unaffected because
the compute was refactored to delegate to
res.company.get_unaffected_earnings_account().

Signed-off-by: Don Kendall <dkendall@ledoweb.com>